GET http://localhost:3003/api/blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjVkZGFhZjA3OThkZjcyNzFiZDFlMmQ3OSIsImlhdCI6MTU3NDYxMjc2MX0.ls3qKaR0tl-NlLRznvv98Caxv5QKMOj-ixiKku8PQLs

{
  "title": "Test titlwdwee",
  "author": "Test Author",
  "url": "Test URL",
  "likes": 123
}
###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
  "author": "Test Author",
  "likes": 123,
  "url": "any",
}
###

PATCH http://localhost:3003/api/blogs/5ddaa8b70e91d8678eaee9e0 HTTP/1.1
        ?author=abc
        &likes=1

###
GET http://localhost:3003/api/blogs/5dd9442c2064405fe4b4fa61 HTTP/1.1

###
DELETE http://localhost:3003/api/blogs/5ddaa9b4e74c5669c616ddb3 HTTP/1.1

###
DELETE http://localhost:3003/api/blogs/5ddaa9b4e74c5669c616ddb3 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhYWFzZSIsImlkIjoiNWRkYTljYmZjMzIzODY1Nzg3MjFlMzdkIiwiaWF0IjoxNTc0NjExNTMyfQ.GpWCfATji_zlmT9zmMUmEq5YdP8PjNw3eslO6_OzRA8

###
DELETE http://localhost:3003/api/blogs/5ddaa9b4e74c5669c616ddb3 HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJpZCI6IjVkZGFhY2E4N2U0Y2JiNmQyOTJjNGYzYyIsImlhdCI6MTU3NDYxMjE0Mn0.UCZCcT7GCEy6yg_5l67MJ3jRYCLIIxGxxMCRk7qkm7Q
