GET http://localhost:3003/api/blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "Test title",
  "author": "Test Author",
  "url": "Test URL",
  "likes": 123
}