GET http://localhost:3001/api/diagnoses HTTP/1.1

###

GET http://localhost:3001/api/patients HTTP/1.1

###

POST http://localhost:3001/api/patients HTTP/1.1
content-type: application/json

{
  "name": "Jon",
  "dateOfBirth": "2020-04-15",
  "gender": "other",
  "ssn": "123-abc-321",
  "occupation": "Jeweller"
}

###

GET http://localhost:3001/api/patients/d2773822-f723-11e9-8f0b-362b9e155667 HTTP/1.1
