DELETE http://localhost:3001/api/persons/5dc6f0e0409cc229867992e3
###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/5d9b88b1385967395a5cfed3
###

PUT http://localhost:3001/api/persons/5d9b88b1385967395a5cfed3
content-type: application/json

{
  "name": "Arto Hellas",
  "number": "040-12345678"
}
###

GET http://localhost:3001/api/persons/123

###

GET http://localhost:3001/unknown/endpoint

###

GET http://localhost:3001/info

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Artzaza2",
  "number": "040-1123453632112"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Johnny"
}

###

DELETE https://salty-savannah-63825.herokuapp.com/api/persons/5db0ac597e2c49000467ef2c

###

GET https://salty-savannah-63825.herokuapp.com/api/persons

###
POST https://salty-savannah-63825.herokuapp.com/api/persons
content-type: application/json

{
  "name": "test",
  "number": "123123123"
}
