DELETE http://localhost:3001/api/persons/5d9b89a90e792e3aada606a4

###

GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/5d9a3f08c525ad6600de92aa
###

PUT http://localhost:3001/api/persons/5d9a3f08c525ad6600de92a3
content-type: application/json

{
  "name": "johnny bravo",
  "number": "1223111121"
}
###

GET http://localhost:3001/api/persons/123

###

GET http://localhost:3001/unknown/endpoint

###

GET http://localhost:3001/info

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Arta",
  "number": "040-1234536321"
}

###

DELETE https://salty-savannah-63825.herokuapp.com/api/persons/5d9e2951ab989b000440e2e0

###

GET https://salty-savannah-63825.herokuapp.com/api/persons

###
POST https://salty-savannah-63825.herokuapp.com/api/persons
content-type: application/json

{
  "name": "test",
  "number": "123"
}
